import type { Announcement, MerchItem, Participant, Zone, ZoneQrCode } from './types';

export const EVENT_END_ISO = '2026-04-21T17:00:00+05:30';

export const ZONES: Zone[] = [
    {
        id: 'ctf',
        type: 'flagship',
        name: 'Capture The Flag',
        shortName: 'CTF',
        tags: ['OVERNIGHT', '12 HRS', 'JEOPARDY'],
        category: 'COMPETITIVE',
        description:
            'Jeopardy-style CTF across Web, Pwn, Reversing, Crypto, Forensics, OSINT and more. 12-hour overnight sprint where top teams win rewards and bragging rights.',
        teamSize: '1-4',
        prizes: 'INR 80,000+',
        duration: '12 HRS',
        format: 'JEOPARDY STYLE',
        points: 200,
        location: 'Central Block - Lab 101',
        registeredCount: 124,
        status: 'open',
        color: '#d4a843',
    },
    {
        id: 'koth',
        type: 'flagship',
        name: 'King of the Hill',
        shortName: 'KOTH',
        tags: ['OVERNIGHT', '8 HRS', 'ATTACK-DEFENCE'],
        category: 'COMPETITIVE',
        description:
            'Attack-defence arena where teams exploit boxes, patch vulnerabilities, and hold access while opponents attempt to dethrone them in an 8-hour overnight warzone.',
        teamSize: '1-3',
        prizes: 'INR 50,000+',
        duration: '8 HRS',
        format: 'ATTACK-DEFENCE',
        points: 200,
        location: 'Central Block - Lab 102',
        registeredCount: 89,
        status: 'open',
        color: '#ef4444',
    },
    {
        id: 'nfc',
        type: 'side',
        name: 'NFC Lock Hunt',
        shortName: 'NFC',
        tags: ['HARDWARE', 'PHYSICAL'],
        category: 'HARDWARE',
        description:
            'Clone NFC badges, crack access controls, and hunt hidden locks across campus in this physical-security challenge.',
        teamSize: 'SOLO',
        points: 50,
        location: 'Central Block - Room 322',
        registeredCount: 67,
        status: 'open',
        color: '#22c55e',
    },
    {
        id: 'hardware',
        type: 'side',
        name: 'Hardware Badge and IoT Village',
        shortName: 'HARDWARE',
        tags: ['HARDWARE', 'HANDS-ON'],
        category: 'HARDWARE',
        description:
            'Solder your own conference badge and explore IoT exploitation stations spanning firmware extraction, UART/JTAG, and wireless sniffing.',
        teamSize: 'SOLO',
        points: 50,
        location: 'Central Block - Lab 203',
        registeredCount: 45,
        status: 'open',
        color: '#f97316',
    },
    {
        id: 'appsec',
        type: 'side',
        name: 'App Sec Zone',
        shortName: 'APPSEC',
        tags: ['WEB', 'MOBILE'],
        category: 'WEB',
        description:
            'Guided web and mobile app pentesting labs covering OWASP Top 10, API abuse, and authentication bypass with real targets.',
        teamSize: 'SOLO',
        points: 50,
        location: 'Central Block - Room 315',
        registeredCount: 93,
        status: 'open',
        color: '#3b82f6',
    },
    {
        id: 'forensics',
        type: 'side',
        name: 'Media Forensics',
        shortName: 'FORENSICS',
        tags: ['FORENSICS', 'AI'],
        category: 'FORENSICS',
        description:
            'Detect manipulated images, inspect metadata, and uncover deepfakes in a forensics-first lab on AI-driven deception.',
        teamSize: 'SOLO',
        points: 50,
        location: 'Central Block - Room 325',
        registeredCount: 58,
        status: 'open',
        color: '#a855f7',
    },
    {
        id: 'arena',
        type: 'side',
        name: 'Hacking Arena',
        shortName: 'ARENA',
        tags: ['SPEED', 'COMPETITIVE'],
        category: 'COMPETITIVE',
        description:
            'Speed-hacking stages with escalating difficulty where operators race the clock, solve challenges, and climb the board.',
        teamSize: 'SOLO',
        points: 75,
        location: 'Central Block - Room 314',
        registeredCount: 112,
        status: 'open',
        color: '#eab308',
    },
    {
        id: 'expo',
        type: 'side',
        name: 'Cyber Expo',
        shortName: 'EXPO',
        tags: ['EXPO', 'NETWORKING'],
        category: 'EXPO',
        description:
            'Industry booths, live demos, and recruiter interactions showcasing modern security tools and workflows.',
        teamSize: 'SOLO',
        points: 25,
        location: 'Central Block - Room 324',
        registeredCount: 201,
        status: 'open',
        color: '#06b6d4',
    },
    {
        id: 'escape',
        type: 'side',
        name: 'Escape Room',
        shortName: 'ESCAPE',
        tags: ['PUZZLE', 'TEAM'],
        category: 'PUZZLE',
        description:
            'Cyber-themed escape room challenge where teams decode ciphers and exploit systems before time runs out.',
        teamSize: '2-4',
        points: 75,
        location: 'Central Block - Room 301',
        registeredCount: 34,
        status: 'open',
        color: '#10b981',
    },
    {
        id: 'gaming',
        type: 'side',
        name: 'Gaming Arena',
        shortName: 'GAMING',
        tags: ['GAMING', 'CASUAL'],
        category: 'GAMING',
        description:
            'Competitive gaming zone for Valorant, CS2, and quick matches between hacking sessions.',
        teamSize: '1-5',
        points: 25,
        location: 'Central Block - Room 221',
        registeredCount: 78,
        status: 'open',
        color: '#8b5cf6',
    },
    {
        id: 'art',
        type: 'side',
        name: 'Art Zone',
        shortName: 'ART',
        tags: ['CREATIVE', 'ART'],
        category: 'CREATIVE',
        description:
            'Cyberpunk art installations, live pixel art, and creative coding demos where hacker culture meets visual expression.',
        teamSize: 'SOLO',
        points: 25,
        location: 'Central Block - Room 316',
        registeredCount: 29,
        status: 'open',
        color: '#ec4899',
    },
];

export const MERCH_ITEMS: MerchItem[] = [
    {
        id: 'tshirt-operator',
        name: 'RECON 2026 T-Shirt - Operator Edition',
        type: 'APPAREL',
        pointsCost: 500,
        stock: 48,
        description:
            'Dark ops tactical tee with RECON 2026 wordmark on front and event callsign print on back.',
        image: '/merch/merch01.png',
    },
    {
        id: 'tshirt-stealth',
        name: 'RECON 2026 T-Shirt - Stealth Edition',
        type: 'APPAREL',
        pointsCost: 500,
        stock: 32,
        description:
            'Minimal stealth colorway with subtle front emblem for operators who move quietly.',
        image: '/merch/merch02.png',
    },
    {
        id: 'cap',
        name: 'RECON 2026 Cap',
        type: 'ACCESSORIES',
        pointsCost: 350,
        stock: 60,
        description:
            'Structured snapback with embroidered RECON 2026 badge for long on-campus ops.',
        image: '/merch/ReCon_Caps3DRender.png',
    },
    {
        id: 'stickers',
        name: 'RECON 2026 Stickers',
        type: 'ACCESSORIES',
        pointsCost: 100,
        stock: 200,
        description:
            'Six-piece holographic sticker pack with RECON logo, zone badges, and tactical marks.',
        image: '/merch/Stickers3DRender.png',
    },
];

export const SEED_ANNOUNCEMENTS: Announcement[] = [
    {
        id: 'ann-ctf-kickoff',
        title: 'CTF KICKOFF IN 30 MINUTES',
        body: 'All CTF participants must be at Central Block Lab 101 by 18:00 sharp. Ensure your environment is set up before arrival.',
        priority: 'URGENT',
        category: 'CTF',
        postedBy: 'RECON COMMAND',
        timeLabel: '2 min ago',
        createdAt: '2026-04-15T17:58:00+05:30',
        unread: true,
    },
    {
        id: 'ann-hardware-open',
        title: 'HARDWARE VILLAGE NOW OPEN',
        body: 'The Hardware Badge and IoT Village is now accepting participants. Head to Lab 203 for badge soldering and IoT exploitation.',
        priority: 'UPDATE',
        category: 'SCHEDULE',
        postedBy: 'RECON COMMAND',
        timeLabel: '45 min ago',
        createdAt: '2026-04-15T17:15:00+05:30',
        unread: true,
    },
    {
        id: 'ann-koth-tonight',
        title: 'KOTH BEGINS AT 22:00 TONIGHT',
        body: 'King of the Hill overnight session starts at 22:00. Team registration closes at 21:30. Late entries will not be accepted.',
        priority: 'INFO',
        category: 'KOTH',
        postedBy: 'RECON COMMAND',
        timeLabel: '1 hr ago',
        createdAt: '2026-04-15T17:00:00+05:30',
    },
    {
        id: 'ann-food-court',
        title: 'FOOD COURT OPERATIONAL UNTIL 02:00',
        body: 'The campus food court will be open through the night for overnight participants. Carry your participant wristband for access.',
        priority: 'GENERAL',
        category: 'GENERAL',
        postedBy: 'RECON COMMAND',
        timeLabel: '2 hrs ago',
        createdAt: '2026-04-15T16:00:00+05:30',
    },
];

export const MOCK_PARTICIPANT: Participant = {
    id: 'OP-2026-0042',
    name: 'Alex Operator',
    email: 'alex@example.com',
    registrationId: 'R2026-042',
    points: 275,
    checkedInZones: ['expo'],
};

export const MOCK_REGISTERED_ZONES = ['ctf', 'hardware', 'expo'];

export const MOCK_QR_CODES: ZoneQrCode[] = [
    { zoneId: 'ctf', code: 'CTF-8X92-KP', isActive: true },
    { zoneId: 'hardware', code: 'HW-4M31-NQ', isActive: true },
    { zoneId: 'expo', code: 'EX-7T55-RF', isActive: false, checkedIn: true, checkedInAt: '2026-04-15 14:18 IST' },
];

export const ZONE_FILTERS = [
    'ALL',
    'FLAGSHIP',
    'HARDWARE',
    'WEB',
    'FORENSICS',
    'COMPETITIVE',
    'EXPO',
    'PUZZLE',
    'GAMING',
    'CREATIVE',
] as const;
